name: Rust CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl
      
      - name: Install musl tools
        run: sudo apt-get update && sudo apt-get install -y musl-tools
      
      - name: Cache Cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: cargo-registry-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-registry-${{ runner.os }}-
      
      - name: Check formatting
        run: cargo fmt --all -- --check
      
      - name: Run clippy
        run: cargo clippy --all-targets --all-features --target x86_64-unknown-linux-musl -- -D warnings
      
      - name: Check workspace
        run: cargo check --workspace --target x86_64-unknown-linux-musl

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg musl-tools
      
      - name: Cache Cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: cargo-registry-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-registry-${{ runner.os }}-
      
      - name: Run tests
        run: cargo test --workspace --target x86_64-unknown-linux-musl
      
      - name: Build workspace (musl static binary)
        run: cargo build --workspace --release --target x86_64-unknown-linux-musl
      
      - name: Verify static linking
        run: |
          file ./target/x86_64-unknown-linux-musl/release/speedy
          ldd ./target/x86_64-unknown-linux-musl/release/speedy 2>&1 | grep -q "not a dynamic executable" && echo "✓ Static binary confirmed" || echo "✗ Not a static binary"
      
      - name: Test CLI help
        run: ./target/x86_64-unknown-linux-musl/release/speedy --help
      
      - name: Test list presets
        run: ./target/x86_64-unknown-linux-musl/release/speedy --list-presets

  test-cross-platform:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: check
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Install FFmpeg (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install ffmpeg
      
      - name: Install FFmpeg (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install ffmpeg -y
          echo "C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\bin" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8
      
      - name: Cache Cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: cargo-registry-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-registry-${{ runner.os }}-
      
      - name: Build
        run: cargo build --workspace --release
      
      - name: Run tests
        run: cargo test --workspace
      
      - name: Test CLI (Unix)
        if: matrix.os != 'windows-latest'
        run: ./target/release/speedy --help
      
      - name: Test CLI (Windows)
        if: matrix.os == 'windows-latest'
        run: .\target\release\speedy.exe --help

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl
      
      - name: Install cargo-audit
        run: cargo install cargo-audit
      
      - name: Run security audit
        run: cargo audit